
before_script:
  - curl -LO https://releases.rancher.com/cli/v0.6.2/rancher-linux-amd64-v0.6.2.tar.gz
  - tar zxf rancher-linux-amd64-v0.6.2.tar.gz
  
build_test:
  script:
    - docker build -t dockerimages.fhcrc.org/batch-dashboard:latest .
    - echo we should really do some testing here
  
  
deploy:
    stage: deploy
    only:
        refs:
            - master
    script:
      - docker login --username $DOCKERIMAGES_USER --password $DOCKERIMAGES_PASS https://dockerimages.fhcrc.org
      - docker push dockerimages.fhcrc.org/batch-dashboard:latest
      - sleep 15
      - rancher-v0.6.2/rancher --url https://ponderosa.fhcrc.org --access-key $RANCHERAPI_KEY --secret-key $RANCHERAPI_SECRET up -d --pull --force-upgrade --confirm-upgrade --stack batch-dashboard --file docker-compose.yml --rancher-file rancher-compose.yml
  
