version: '2'
services:
  batch-dashboard:
    image: dockerimages.fhcrc.org/fredhutch/batch-dashboard:latest
    stdin_open: true
    ports:
      - "8001"
    labels:
      io.rancher.container.pull_image: always

    restart: always

    secrets:
    - BATCH_DASHBOARD_AWS_ACCESS_KEY
    - BATCH_DASHBOARD_AWS_REGION
    - BATCH_DASHBOARD_SECRET_KEY
    - BATCH_DASHBOARD_APP_SECRET

secrets:
  BATCH_DASHBOARD_AWS_ACCESS_KEY:
    external: true
  BATCH_DASHBOARD_AWS_REGION:
    external: true
  BATCH_DASHBOARD_APP_SECRET:
    external: true
  BATCH_DASHBOARD_SECRET_KEY:
    external: true
